title: Ръководство — Хижа Септември
description: Наръчник за администриране на сайта на Хижа Септември
theme: just-the-docs
plugins:
  - jekyll-relative-links
color_scheme: light
heading_anchors: true
relative_links:
  enabled: true
  collections: false
aux_links:
  "Отвори septemvrihut.bg": "https://septemvrihut.bg"
defaults:
  - scope:
      path: ""
    values:
      layout: default
